/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantelcampo;

import javax.swing.JOptionPane;

/**
 *
 * @author LAB-USR-PT116-C409
 */
public class Mesas extends javax.swing.JFrame {

    /**
     * Creates new form Mesas
     */
    
    public static String NumMesa = "";
    public Mesas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Mesa9 = new javax.swing.JButton();
        Mesa10 = new javax.swing.JButton();
        Mesa11 = new javax.swing.JButton();
        Mesa12 = new javax.swing.JButton();
        Mesa13 = new javax.swing.JButton();
        Mesa14 = new javax.swing.JButton();
        Mesa15 = new javax.swing.JButton();
        Mesa16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3643764-back-backward-left-reply-turn_113415.png"))); // NOI18N
        jButton3.setText("ATRAS");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout_90894.png"))); // NOI18N
        jButton4.setText("SALIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Mesa9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa9.setText("1");
        Mesa9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa9.setIconTextGap(-20);
        Mesa9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa9ActionPerformed(evt);
            }
        });

        Mesa10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa10.setText("3");
        Mesa10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa10.setIconTextGap(-20);
        Mesa10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa10ActionPerformed(evt);
            }
        });

        Mesa11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa11.setText("2");
        Mesa11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa11.setIconTextGap(-20);
        Mesa11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa11ActionPerformed(evt);
            }
        });

        Mesa12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa12.setText("4");
        Mesa12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa12.setIconTextGap(-20);
        Mesa12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa12ActionPerformed(evt);
            }
        });

        Mesa13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa13.setText("5");
        Mesa13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa13.setIconTextGap(-20);
        Mesa13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa13ActionPerformed(evt);
            }
        });

        Mesa14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa14.setText("6");
        Mesa14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa14.setIconTextGap(-20);
        Mesa14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa14ActionPerformed(evt);
            }
        });

        Mesa15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa15.setText("7");
        Mesa15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa15.setIconTextGap(-20);
        Mesa15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa15ActionPerformed(evt);
            }
        });

        Mesa16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Mesa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        Mesa16.setText("8");
        Mesa16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Mesa16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mesa16.setIconTextGap(-20);
        Mesa16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Mesa16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mesa16ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mesa9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mesa14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mesa9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mesa13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mesa15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int Descicion =  JOptionPane.showConfirmDialog(null,"¿Segro desea Quitar la fila de la tabla?");
        if(Descicion==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Mesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa9ActionPerformed
        // TODO add your handling code here:
        NumMesa = "1";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa9ActionPerformed

    private void Mesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa10ActionPerformed
        // TODO add your handling code here:
        NumMesa = "3";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa10ActionPerformed

    private void Mesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa11ActionPerformed
        // TODO add your handling code here:
        NumMesa = "2";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa11ActionPerformed

    private void Mesa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa12ActionPerformed
        // TODO add your handling code here:
        NumMesa = "4";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa12ActionPerformed

    private void Mesa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa13ActionPerformed
        // TODO add your handling code here:
        NumMesa = "5";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa13ActionPerformed

    private void Mesa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa14ActionPerformed
        // TODO add your handling code here:
        NumMesa = "6";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa14ActionPerformed

    private void Mesa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa15ActionPerformed
        // TODO add your handling code here:
        NumMesa = "7";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa15ActionPerformed

    private void Mesa16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mesa16ActionPerformed
        // TODO add your handling code here:
        NumMesa = "8";
        DetalleMesa Mesa = new DetalleMesa();
        Mesa.setVisible(true); 
    }//GEN-LAST:event_Mesa16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mesa10;
    private javax.swing.JButton Mesa11;
    private javax.swing.JButton Mesa12;
    private javax.swing.JButton Mesa13;
    private javax.swing.JButton Mesa14;
    private javax.swing.JButton Mesa15;
    private javax.swing.JButton Mesa16;
    private javax.swing.JButton Mesa9;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
